package com.pokesite.site.pokesite.resources.persistence.entity

import javax.persistence.Entity
import javax.persistence.Id
import javax.persistence.Table

@Entity
@Table(name = "pokemon_imgs")
data class PokemonImgs(
    @Id
    val id: Int,
    val back_default : String?,
    val back_female : String?,
    val back_shiny : String?,
    val back_shiny_female : String?,
    val front_default : String?,
    val front_female : String?,
    val front_shiny : String?,
    val front_shiny_female : String?,
    val dream_world_front_default : String?,
    val dream_world_front_female : String?,
    val home_front_default : String?,
    val home_front_female : String?,
    val home_front_shiny : String?,
    val home_front_shiny_female : String?,
    val official_artwork_front_default : String?,
    val red_blue_back_default : String?,
    val red_blue_back_gray : String?,
    val red_blue_back_transparent : String?,
    val red_blue_front_default : String?,
    val red_blue_front_gray : String?,
    val red_blue_front_transparent : String?,
    val yellow_back_default : String?,
    val back_gray_back_transparent : String?,
    val back_gray_front_default : String?,
    val back_gray_front_gray : String?,
    val back_gray_front_transparent : String?,
    val crystal_back_default : String?,
    val crystal_back_shiny : String?,
    val crystal_back_shiny_transparent : String?,
    val crystal_back_transparent : String?,
    val crystal_front_default : String?,
    val crystal_front_shiny : String?,
    val crystal_front_shiny_transparent : String?,
    val crystal_front_transparent : String?,
    val gold_back_default : String?,
    val gold_back_shiny : String?,
    val gold_front_default : String?,
    val gold_front_shiny : String?,
    val gold_front_transparent : String?,
    val silver_back_default : String?,
    val silver_back_shiny : String?,
    val silver_front_default : String?,
    val silver_front_shiny : String?,
    val silver_front_transparent : String?,
    val emerald_front_default : String?,
    val emerald_front_shiny : String?,
    val firered_leafgreen_back_default : String?,
    val firered_leafgreen_back_shiny : String?,
    val firered_leafgreen_front_default : String?,
    val firered_leafgreen_front_shiny : String?,
    val ruby_sapphire_back_default : String?,
    val ruby_sapphire_back_shiny : String?,
    val ruby_sapphire_front_default : String?,
    val ruby_sapphire_front_shiny : String?,
    val diamond_pearl_back_default : String?,
    val diamond_pearl_back_female : String?,
    val diamond_pearl_back_shiny : String?,
    val diamond_pearl_back_shiny_female : String?,
    val diamond_pearl_front_default : String?,
    val diamond_pearl_front_female : String?,
    val diamond_pearl_front_shiny : String?,
    val diamond_pearl_front_shiny_female : String?,
    val heartgold_soulsilver_back_default : String?,
    val heartgold_soulsilver_back_female : String?,
    val heartgold_soulsilver_back_shiny : String?,
    val heartgold_soulsilver_back_shiny_female : String?,
    val heartgold_soulsilver_front_default : String?,
    val heartgold_soulsilver_front_female : String?,
    val heartgold_soulsilver_front_shiny : String?,
    val heartgold_soulsilver_front_shiny_female : String?,
    val platinum_back_default : String?,
    val platinum_back_female : String?,
    val platinum_back_shiny : String?,
    val platinum_back_shiny_female : String?,
    val platinum_front_default : String?,
    val platinum_front_female : String?,
    val platinum_front_shiny : String?,
    val platinum_front_shiny_female : String?,
    val black_white_animated_back_default : String?,
    val black_white_animated_back_female : String?,
    val black_white_animated_back_shiny : String?,
    val black_white_animated_back_shiny_female : String?,
    val black_white_animated_front_default : String?,
    val black_white_animated_front_female : String?,
    val black_white_animated_front_shiny : String?,
    val black_white_animated_front_shiny_female : String?,
    val black_white_back_default : String?,
    val black_white_back_female : String?,
    val black_white_back_shiny : String?,
    val black_white_back_shiny_female : String?,
    val black_white_front_default : String?,
    val black_white_front_female : String?,
    val black_white_front_shiny : String?,
    val black_white_front_shiny_female : String?,
    val omegaruby_alphasapphire_front_default : String?,
    val omegaruby_alphasapphire_front_female : String?,
    val omegaruby_alphasapphire_front_shiny : String?,
    val omegaruby_alphasapphire_front_shiny_female : String?,
    val x_y_front_default : String?,
    val x_y_front_female : String?,
    val x_y_front_shiny : String?,
    val x_y_front_shiny_female : String?,
    val generation_vii_icons_front_default : String?,
    val generation_vii_icons_front_female : String?,
    val ultra_sun_ultra_moon_front_default : String?,
    val ultra_sun_ultra_moon_front_female : String?,
    val ultra_sun_ultra_moon_front_shiny : String?,
    val ultra_sun_ultra_moon_front_shiny_female : String?,
    val generation_viii_icons_front_default : String?,
    val generation_viii_icons_front_female : String?
)