version: '3.8'
services:
  db_2:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db_2:/var/lib/postgresql/data
volumes:
  db_2:
    driver: local